# Context Root
server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: zuul-server
# ================================
# Mysql DB configuration
  datasource:
    url: jdbc:mysql://localhost:3306/micro
    username: root
    password: billa
    driver-class-name: com.mysql.cj.jdbc.Driver
# Connection Pooling- ref PoolProperties
    tomcat:
      initial-size: 5
      max-active: 20
      max-idle: 10
      min-idle: 5
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
## ==============================================================================
## App Properties
#dt:
#   app:
#      jwtSecret: gauditdev
#      jwtExpirationMs: 86400000
